name: Fetch News
on:
  schedule:
    - cron: '30 1-16 * * *'  # Runs every hour between 07:00 and 22:00 IST (30 minutes past each hour)
  workflow_dispatch:  # Enable manual trigger

jobs:
  fetch_news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run fetch_news.py
        run: python fetch_news.py

      - name: Commit and push updated news
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/news.json
          git commit -m "Update news"
          git push
